// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables and log helpful error messages
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [];
  if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  
  console.error(
    `❌ Missing required environment variables: ${missing.join(', ')}\n` +
    `\nPlease set these in your production environment:\n` +
    `- VITE_SUPABASE_URL: Your Supabase project URL\n` +
    `- VITE_SUPABASE_PUBLISHABLE_KEY: Your Supabase anon/public key\n\n` +
    `You can find these in your Supabase project settings under API.\n` +
    `\nCurrent environment: ${import.meta.env.MODE}`
  );
  
  // Use placeholder values to prevent immediate crashes, but the app won't function properly
  // The app will show errors when trying to use Supabase
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);